### ISSUE TITLE
[Feature Request] Persistence

### ISSUE THREAD

**Issue by MichaelTSS** [janogonzalez/priorityqueuejs#12]
Hello,

I guess this issue isn't as much as a feature request as it is a design question.
Imagine you have a pool of workers (say you manage it with PM2 or the Cluster built-in module) and a web-server on the same machine. The web-server sends to one of the workers a sync or async job, that you want to implement as a PriorityQueue.

If the job crashes or exits unexpectedly, the PriorityQueue data would be lost. Wouldn't it be great if one could start the job again and pick up where the previous one left off?

Please give your thought about it,

**Comment by janogonzalez** [comment]
Hey Michael,

I want to keep the library as small as possible, so I prefer not to add features that won't be widely used.
That being said, maybe you can implement such behavior on your own with a small serialization function, for example you can use something like https://github.com/skeeto/resurrect-js and persist the queue in a serialized form.

**Comment by MichaelTSS** [comment]
Thanks @janogonzalez that makes sense. Thanks for the tip I haven't heard about Resurrect.JS before
