### ISSUE TITLE
Enqueing doesn't work correctly.

### ISSUE THREAD

**Issue by mranon0007** [janogonzalez/priorityqueuejs#13]
I am using Node v8.10.0 and using the latest version of priorityqueuejs but the same code given in the Readme file doesn't work as expected when I modify it a bit. For example consider the following code:

```
var queue = new PriorityQueue(function (a, b) {
    if (a.sender > b.sender) {
        return 1
    } else if (a.sender == b.sender) {
        return 0
    } else {
        return -1
    }
});
queue.enq({
    "sender": "1"
});
queue.enq({
    "sender": "4"
});
queue.enq({
    "sender": "3"
});
queue.enq({
    "sender": "2"
});

queue.forEach(function(val, i) {
    console.log(val);
})
```
When I print the output, instead of getting the output as 1,2,3,4, I get 4,2,3,1.
```
{ sender: '4' }
{ sender: '2' }
{ sender: '3' }
{ sender: '1' }
```

**Comment by janogonzalez** [comment]
In your case the result is expected, because the comparator function is giving more priority to the larger elements (returns `1` if `a > b`).

That being said, I wasn't very convinced of having a `forEach` on this library to avoid confusion and possible problems. Maybe I should have let it out.

**Comment by janogonzalez** [comment]
Anyway, thanks for reaching out. I hope this clarifies things, maybe I'll change the example in the README or explain a little more to avoid confusion.
