### ISSUE TITLE
DEFAULT_COMPARATOR for numbers?

### ISSUE THREAD

**Issue by smilingthax** [janogonzalez/priorityqueuejs#4]
> PriorityQueue.DEFAULT_COMPARATOR(10,2)
    -1
    > PriorityQueue.DEFAULT_COMPARATOR(new Number(10),new Number(2))
    8

From reading the documentation, my expectation was that numbers (i.e. `typeof num === 'number'`) would be compared numerically, not as strings. But only Numbers (i.e. `typeof num === object`, `num instanceof Number`) are handled specially in the code.

I'd suggest either to mention this explicitly in the documentation, or to adjust the implementation.

**Comment by janogonzalez** [comment]
I'm the worst maintainer EVER, after more than one year I will look into this.

**Comment by janogonzalez** [comment]
Fixed!
