### ISSUE TITLE
Queue behaves like a stack?

### ISSUE THREAD

**Issue by myndzi** [janogonzalez/priorityqueuejs#6]
Between two items of equal priority, the last one added is dequeued first. Can you implement the reverse behavior?

    > var foo = new PriorityQueue(function (a, b) { return b.pri - a.pri; });
    undefined
    > foo.enq({ pri: 1, val: 1 });
    1
    > foo.enq({ pri: 1, val: 2 });
    2
    > foo.deq()
    { pri: 1, val: 2 }

**Comment by janogonzalez** [comment]
I will take a look into it!

**Comment by janogonzalez** [comment]
fixed by @xgbuils :metal:
